library(devtools)
Sys.setlocale(category="LC_CTYPE",locale="C")
## create('C:/Users/lipe6002/Downloads/tobed/RpackageDev/storematching')
setwd('C:/Users/lipe6002/Downloads/tobed/RpackageDev/storematching')
dir()
## file.edit('DESCRIPTION')
load_all()
document()
build(binary = T)
detach("package:storematching", unload=TRUE)
# check()
install.packages("C:/Users/lipe6002/Downloads/tobed/RpackageDev/storematching_0.1.1.zip",repos=NULL)
library(storematching)
