library(devtools)
Sys.setlocale(category="LC_CTYPE",locale="C")
## create('C:/Users/lipe6002/Downloads/tobed/RpackageDev/piececollect')
setwd('C:/Users/lipe6002/Downloads/tobed/RpackageDev/piececollect')
dir()
## file.edit('DESCRIPTION')
load_all()
document()
build(binary = FALSE)
detach("package:piececollect", unload=TRUE)
## check()
install.packages("../piececollect_0.1.0.tar.gz",repos = NULL)
library(piececollect)
