library(devtools)
## create('C:/Users/lipe6002/Downloads/tobed/RpackageDev/dapre')
setwd('C:/Users/lipe6002/Downloads/tobed/RpackageDev/dapre')
dir()
## file.edit('DESCRIPTION')
load_all()
document()
build(binary = FALSE)
detach("package:dapre", unload=TRUE)
## check()
install.packages("../dapre_0.1.0.tar.gz",repos = NULL)
library(dapre)
