library(devtools)
## create('C:/Users/lipe6002/Downloads/tobed/RpackageDev/pipmodel')
setwd('C:/Users/lipe6002/Downloads/tobed/RpackageDev/pipmodel')
dir()
## file.edit('DESCRIPTION')
load_all()
document()
build(binary = FALSE)
detach("package:pipmodel", unload=TRUE)
## check()
install.packages("../pipmodel_0.1.0.tar.gz",repos = NULL)
library(pipmodel)
